Queries to backfill active_users_aggregates.
mozilla/bigquery-backfill pull request #42
Opened 2024-04-26 22:49 UTC by lucia-vargas-a

Implements [DENG-3543](https://mozilla-hub.atlassian.net/browse/DENG-3543).

2024-04-26 22:50 UTC, lucia-vargas-a commented on backfill/2024-04-26-active_users_aggregates/focus_ios_query.sql
> +    um.submission_date >= '2021-12-01' AND um.submission_date <= CURRENT_DATE
Earliest data available.

2024-04-26 22:50 UTC, lucia-vargas-a commented on backfill/2024-04-26-active_users_aggregates/klar_ios_query.sql
> +    um.submission_date >= '2022-12-18' AND um.submission_date <= CURRENT_DATE
Earliest data available.

2024-04-29 17:36 UTC, bochocki requested changes
Just the one small issue. Otherwise looks good.

2024-04-29 17:36 UTC, bochocki commented on backfill/2024-04-26-active_users_aggregates/fenix_query.sql
> +  COUNT(DISTINCT client_id) < 28 AS monthly_users,
I think this may be a copypasta error. 
```suggestion
  COUNT(DISTINCT client_id) AS monthly_users,
```

2024-05-02 19:35 UTC, bochocki approved these changes

2024-05-10 12:01 UTC, merged